### ISSUE TITLE
About some information about todo project?

### ISSUE THREAD

**Issue by priyanshu-kun** [Sushant2/Todo-App#4]
### Hii, Is this todo app project from anjela yu web developer bootcamp?

**Comment by Sushant2** [comment]
> ### Hii, Is this todo app project from anjela yu web developer bootcamp?

Yahh! 
That's why modifying the UI

**Comment by priyanshu-kun** [comment]
Bro you should hide your mongodb atlas cluster link cause It is now publicly visible and anyone will use that to create his database.
You should use dotenv module to hide this **or** put it on different js file and import it within your database file and use .gitignore to ignore dotenv file or js file.

**Comment by Sushant2** [comment]
> Bro you should hide your mongodb atlas cluster link cause It is now publicly visible and anyone will use that to create his database.
> You should use dotenv module to hide this **or** put it on different js file and import it within your database file and use .gitignore to ignore dotenv file or js file.

Thanks for ur suggestions!
I forgot to change the file later on as it was created few months back, when i don't know about environment variables!
I'll change that soon!!!

**Comment by priyanshu-kun** [comment]
Are you anime fan brother Cause I saw light yagami picture in your profile.

**Comment by Sushant2** [comment]
> Are you anime fan brother Cause I saw light yagami picture in your profile.

Yesss!
Death Note is my fav. anime!!!

**Comment by priyanshu-kun** [comment]
Yeah It is the one of the best anime.
Are you ever watch demon slayer this is also greatest anime I am ever seen.

**Comment by Sushant2** [comment]
Yes!
I used to watch it earlier!!!
It is also good to watch!!

**Comment by priyanshu-kun** [comment]
You know hindi language?

**Comment by Sushant2** [comment]
yep, bro!
I'm an indian!!!
