### ISSUE TITLE
"Plus" button not properly centered

### ISSUE THREAD

**Issue by NabeelAhmed1721** [Sushant2/Todo-App#7]
It is probably a quick CSS fix but the plus button isn't properly centered.

<img width="537" alt="Screen Shot 2020-10-14 at 7 55 46 AM" src="https://user-images.githubusercontent.com/47062026/95985506-acf64700-0df2-11eb-86de-8f462445cfc0.png">

**Comment by Sushant2** [comment]
It's working fine in the recently updated code!!!

**Comment by NabeelAhmed1721** [comment]
What browser are you using?

**Comment by Sushant2** [comment]
Chrome!
Actually u'r clcicking on the webapp link, which isn't yet updated!!!
Ig, that'why u r facing this issue!!!

**Comment by NabeelAhmed1721** [comment]
then update the webapp link??
